# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
# image: busybox:latest

cache:
  paths:
    - node_modules/

before_script:
  - echo "Before script section"
  - echo "For example you might run an update here or install a build dependency"
  - echo "Or perhaps you might print out some debugging details"



test1:
  stage: test
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"


build1:
  stage: build
  script:
    - echo "Do your build here"
    - npm install && NODE_ENV=production npm run build
    #- npm run build
    #- pm2 delete bookmap-site



deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
    #- pm2 start npm --name "bookmap-site" -- start
    - pm2 restart bookmap-site
