export const text: { [index: string]: any } = {
  h1: 'Pricing and Packages',
  h2: 'Trade cryptocurrencies and get many features with Bookmap desktop application ',
  l1: 'MONTHLY',
  l2: 'YEARLY',
  l4: 'Save 16%',
  t1: 'digital',
  t2: 'digital+',
  r1: 'Bookmap desktop application',
  r2: 'Real-time market data ',
  r3: 'Simulated & Live Trading ',
  r4: 'API for custom indicators & automated strategies ',
  r5: 'Supported exchanges ',
  r6: 'Max # of trading pairs\n' + 'viewable at the same time',
  r7: 'Backfill data',
  r8: 'Record and Replay',
  r9: 'VWAP',
  r10: 'Correlation Tracker',
  r11: 'Advanced Education',
  td1: '> 20 Crypto exchanges',
  link12: 'https://bookmap.com/members/signup/gv3uiH6Hi?product_id_page-0[]=170-170',
  link22: 'https://bookmap.com/members/signup/gv3uiH6Hi?product_id_page-0[]=171-171',
}
